apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-appset-jsonpath
  namespace: argocd # Ensure this is the Argo CD namespace
spec:
  generators:
  - git:
      repoURL: https://github.com/TejaswiniOpsmx/argo-customer-demo.git # Replace with your Git repo URL
      revision: new-test
      files:
      - path: "source-apps/*.json"
  template: # Correct indentation here
    metadata:
      name: '{{clusterName}}-guestbook'
      namespace: argocd # Ensure this is the Argo CD namespace
    spec:
      project: default
      source:
        repoURL: https://github.com/TejaswiniOpsmx/argo-customer-demo.git # Replace with your Git repo URL
        targetRevision: new-test
        path: '{{appPath}}' # Path from the Json file.
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
