apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: sample-app
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: "https://github.com/TejaswiniOpsmx/argo-customer-demo.git"
        revision: "new-test"
        files:
          - path: "source-apps/config.json"
  template:
    metadata:
      name: "{{.applications.name}}"
    spec:
      project: "default"
      source:
        repoURL: "{{.applications.repoURL}}"
        targetRevision: "{{.applications.targetRevision}}"
        path: "{{.applications.path}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{.applications.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
