apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: source-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/TejaswiniOpsmx/argo-customer-demo.git
        revision: new-test
        files:
          - path: "source-apps/**/*.yaml"
        values:
          base_dir: "source-apps"
  template:
    metadata:
      name: '{{ .values.base_dir | replace "/" "-" }}-{{ .path | basename | replace "/" "-" }}'  # Ensure unique name    spec:
      project: default
      source:
        repoURL: "https://github.com/TejaswiniOpsmx/argo-customer-demo.git"
        targetRevision: "new-test"
        path: '{{ .values.base_dir }}/{{ .path.basename }}'  # Properly resolve the base directory
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
